### ISSUE TITLE
html特殊文字のエンコードとデコードの動き

### ISSUE THREAD

**Issue by masasato** [gm2bv/mdDog#14]
html固有の特殊文字（例：&amp;amp;）を入力して更新を行い、再度更新を行なおうとすると入力欄が表示文字（例：&）に変換されています。データが入力者の意図とは異なるかと思われます。

**Comment by gm2bv** [comment]
以下のリヴィジョンでの不具合対応で治ったようです。
455f6c0a5c736c4e209d1576a31f0db64194350e

ご確認ください
