### ISSUE TITLE
ヘッダーが欲しい

### ISSUE THREAD

**Issue by mth1d** [gm2bv/mdDog#15]
+ 長い文章や似ている内容を読んでいる
+ 何ページが戻ってhogehoge項目を参照したい

上記のような「開いているページが“どの章”の“どの項目”」か
すぐに分かるようになっていると可読性があがります。  

例）
ページ内に出てきた最初の見出しの1、2をヘッダーに出す
見出しのないページは前のページのヘッダーを引き継ぐ

**Comment by gm2bv** [comment]
見出しマップを機能追加しました。
これでドキュメントの全体像を掴みやすくなったと思っているのですがどうでしょうか？
また「開いてるページ（見ている箇所）がどの章のどの項目か？」という視点で判断すると、
見出しマップだけでは要望に対して十分に対策できていない可能性があります。
この点も今一度見てみてどのように感じるかご教示くださいませ。

**Comment by mth1d** [comment]
見出しマップ確認しました。

編集側のHeadlineであってますでしょうか？
編集側で便利に利用できそうです。ありがとうございます。

>開いてるページ（見ている箇所）がどの章のどの項目か？

編集ではなく“読む”という状況の場合ですが
「最新版アウトライン」で確認すると思いますが
ヘッダーは、やはり欲しいところです。

紙に出さずにブラウザで読むときには、ブラウザの検索で
色々と飛んでいったりもしますので。。
