### ISSUE TITLE
コードブロック（pre表示）にタグや＃を記入すると、editやプレビューのレイアウトが崩れてしまう

### ISSUE THREAD

**Issue by mth1d** [gm2bv/mdDog#19]
バッククォートの3連で囲むとpre表示が可能と思いますが
htmlやapacheの設定ファイルxmlのようなタグが入っていると
editやプレビューのレイアウトが崩れてしまいます。

また半角の「＃」（コードのコメント等の）が含まれていると、見出し扱いになってしまい
pre表示ができません。

**Comment by gm2bv** [comment]
コードブロックないのタグについては、スタイルシートの手直しで治りました。ご確認ください。

コードブロックの'#'については、使用しているライブラリの問題で対応には時間がかかりそうです。現状の回避策としては、コードブロックを使うときに３連のバッククォートを使わずに半角スペース４つを各行の先頭に入れる方法があります。

**Comment by mth1d** [comment]
コードブロック内のタグの修正ありがとうございました。
コードブロックの'#'を利用するときには半角スペース4つで対応します。
