### ISSUE TITLE
1タグの中を分割（追加）するような編集をすると、更新後に編集箇所がずれていってしまう

### ISSUE THREAD

**Issue by mth1d** [gm2bv/mdDog#2]
編集バッファにしてmarkdownで記述して更新すると、自動的にタグごとに分割されます。

例）
+ h1
+ h2
+ P
+ TABLE

この状態でPの箇所を編集して、Pが増えるようにして更新したとします。

例）
+ h1
+ h2
+ P　←空行を入れて文章を追加すると
+ P　←ここにPが増える
+ TABLE

追加された方の文章（P）を編集モードにすると、1つずれてTABLEの内容が表示されてしまいます。

**Comment by gm2bv** [comment]
仕組み上割り切りにしたいのですが、現状のUIだとおっしゃる通り不自然な動きとなっています。
とりあえずバグとして対応し、打開策を探します
