### ISSUE TITLE
文書にタグやラベルを付けて絞り込みができるようにしてほしい

### ISSUE THREAD

**Issue by mth1d** [gm2bv/mdDog#24]
本来の使い方とは異なるかもしれませんが
慣れてくると仕様書以外の文書もこちらにまとめておきたくなります。

文書例）
+ 仕様書（想定）
+ 操作手順書、マニュアル
+ 学習資料

文書が多くなってきたときには種類別に絞り込む機能が欲しいですし
仕様書だけの場合でも仕様書の種類で分類ができる仕組みが
あれば便利かと思います。
※タグ、ラベル名は自由に付けられる方がよいです。

----

ラベル名例1）
+ 仕様書
+ 手順書
+ 学習資料

ラベル名例2）
+ 仕様書
+ 開発
+ 評価

**Comment by gm2bv** [comment]
6531cc56e38f73272ef2e8c372f527923b749413

以上のコミットで一覧からタグ付けしたドキュメントを検索できるようにしました
タグ付けは一覧のタグマークをクリックして行ってください
